# ==============================================================================
# COMPILER SETTINGS
# ==============================================================================

# CC: The compiler to use (GCC)
CC = gcc

# CFLAGS: Flags for the compiler
# -Wall -Wextra: Enable most compiler warnings for better code quality
# -std=c11: Use the C11 standard
# -g: Include debugging information for use with GDB
CFLAGS = -Wall -Wextra -std=c11 -g

# ==============================================================================
# TARGETS AND DIRECTORIES
# ==============================================================================

# The final executable name for the spreadsheet program
TARGET = sheet
EXE = $(TARGET).exe

# LaTeX compiler path - specifically configured for a Windows MiKTeX installation
PDFLATEX = "C:/Program Files/MiKTeX/miktex/bin/x64/pdflatex.exe"

# ==============================================================================
# SOURCE AND OBJECT FILES
# ==============================================================================

# List of all C source files required for the project
SRCS = main.c interface.c parser.c evaluator.c graph.c

# Object files: Automatically generated by replacing .c with .o from the SRCS list
OBJS = $(SRCS:.c=.o)

# ==============================================================================
# BUILD RULES
# ==============================================================================

# Default 'make' command. It triggers the compilation of the TARGET.
all: $(TARGET)

# Linking: Combines all .o object files into the final executable.
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

# Pattern Rule: Compiles any .c file into a .o file.
# It depends on spreadsheet.h, so if the header changes, all files re-compile.
# $< refers to the .c file, $@ refers to the .o file.
%.o: %.c spreadsheet.h
	$(CC) $(CFLAGS) -c $< -o $@

# ==============================================================================
# UTILITY AND AUTOMATION RULES
# ==============================================================================

# 'make test': Compiles and runs the test suite.
# @echo hides the command from the terminal, showing only the message.
test: $(TARGET)
	@echo "Running test suite..."
	$(CC) $(CFLAGS) tests/test.c -o test_suite.exe
	./test_suite.exe
	rm -f test_suite.exe temp_test.txt

# 'make report': Automates the LaTeX PDF generation.
# Runs pdflatex twice to ensure table of contents and references are updated correctly.
report: report.tex
	@echo "Generating PDF report..."
	$(PDFLATEX) report.tex
	$(PDFLATEX) report.tex
	@echo "Report generated: report.pdf"

# 'make clean': Deletes all generated files to allow for a fresh "clean" build.
# Useful for resolving compilation artifacts or preparing a zip for submission.
clean:
	rm -f $(TARGET).exe *.o test_suite.exe report.pdf temp_test.txt test_input.txt	